Prefixes = {
"Acorn", 
"Adder", 
"Alder", 
"Amber", 
"Ant", 
"Apple", 
"Arch", 
"Ash", 
"Aspen", 
"Badger", 
"Bark", 
"Bay", 
"Bee", 
"Beech", 
"Beetle", 
"Bella", 
"Berry", 
"Big", 
"Billy", 
"Birch", 
"Bird", 
"Black", 
"Blaze", 
"Blizzard", 
"Bloom", 
"Blossom", 
"Blue", 
"Bluebell", 
"Boulder", 
"Bounce", 
"Bracken", 
"Bramble", 
"Brave", 
"Breeze", 
"Briar", 
"Bright", 
"Brindle", 
"Bristle", 
"Broken", 
"Brook", 
"Brown", 
"Brush", 
"Bubbling", 
"Bug", 
"Bumble", 
"Buzzard", 
"Cedar", 
"Cherry", 
"Chestnut", 
"Chive", 
"Cinder", 
"Cinnamon", 
"Claw", 
"Clear", 
"Cloud", 
"Clover", 
"Cone", 
"Copper", 
"Creek", 
"Cricket", 
"Crooked", 
"Crouch", 
"Crow", 
"Curl", 
"Curly", 
"Cypress", 
"Daisy", 
"Dandelion", 
"Dangling", 
"Dapple", 
"Dark", 
"Dawn", 
"Dead", 
"Deer", 
"Dew", 
"Doe", 
"Dove", 
"Down", 
"Drizzle", 
"Drift", 
"Duck", 
"Dusk", 
"Dust", 
"Eagle", 
"Ebony", 
"Echo", 
"Eel", 
"Elder", 
"Ember", 
"Fallen", 
"Fallow", 
"Fawn", 
"Feather", 
"Fennel", 
"Fern", 
"Ferret", 
"Fidget", 
"Fin", 
"Finch", 
"Fir", 
"Fire", 
"Flail", 
"Flame", 
"Flash", 
"Flax", 
"Fleet", 
"Flicker", 
"Flint", 
"Flip", 
"Flower", 
"Flutter", 
"Fly", 
"Fog", 
"Fox", 
"Freckle", 
"Fringe", 
"Frog", 
"Frond", 
"Frost", 
"Furze", 
"Fuzzy", 
"Gale", 
"Golden", 
"Goose", 
"Gorse", 
"Grass", 
"Gravel", 
"Gray", 
"Green", 
"Gull", 
"Hail", 
"Half", 
"Hare", 
"Harry", 
"Harvey", 
"Hatch", 
"Haven", 
"Hawk", 
"Hay", 
"Hazel", 
"Heather", 
"Heavy", 
"Heron", 
"Hickory", 
"Hill", 
"Hollow", 
"Holly", 
"Honey", 
"Hoot", 
"Hop", 
"Hope", 
"Hound", 
"Ice", 
"Ivy", 
"Jagged", 
"Jay", 
"Jump", 
"Juniper", 
"Kestrel", 
"Kink", 
"Kite", 
"Lake", 
"Larch", 
"Lark", 
"Lavender", 
"Leaf", 
"Leopard", 
"Lichen", 
"Light", 
"Lightning", 
"Lily", 
"Lion", 
"Little", 
"Lizard", 
"Log", 
"Long", 
"Lost", 
"Loud", 
"Low", 
"Lynx", 
"Maggot", 
"Mallow", 
"Maple", 
"Marigold", 
"Marsh", 
"Meadow", 
"Midge", 
"Milk", 
"Milkweed", 
"Minnow", 
"Mint", 
"Mist", 
"Mistle", 
"Misty", 
"Mole", 
"Monkey", 
"Moon", 
"Morning", 
"Moss", 
"Mossy", 
"Moth", 
"Mottle", 
"Mouse", 
"Mud", 
"Mumble", 
"Myrtle", 
"Nectar", 
"Needle", 
"Nettle", 
"Newt", 
"Night", 
"Nut", 
"Oak", 
"Oat", 
"Odd", 
"Olive", 
"One", 
"Otter", 
"Owl", 
"Pale", 
"Parsley", 
"Patch", 
"Pear", 
"Pebble", 
"Perch", 
"Petal", 
"Pigeon", 
"Pike", 
"Pine", 
"Pink", 
"Plum", 
"Pod", 
"Pool", 
"Poppy", 
"Pounce", 
"Prickle", 
"Primrose", 
"Puddle", 
"Quail", 
"Quick", 
"Quiet", 
"Rabbit", 
"Ragged", 
"Rain", 
"Rat", 
"Raven", 
"Red", 
"Reed", 
"Ridge", 
"Riley", 
"Ripple", 
"River", 
"Robin", 
"Rock", 
"Rook", 
"Root", 
"Rose", 
"Rowan", 
"Rubble", 
"Running", 
"Rush", 
"Russet", 
"Rye", 
"Sage", 
"Sand", 
"Sandy", 
"Scorch", 
"Sedge", 
"Seed", 
"Shade", 
"Shadow", 
"Sharp", 
"Shattered", 
"Sheep", 
"Shell", 
"Shimmer", 
"Shining", 
"Shivering", 
"Short", 
"Shred", 
"Shrew", 
"Shy", 
"Silver", 
"Sky", 
"Slate", 
"Sleek", 
"Slight", 
"Sloe", 
"Small", 
"Smoke", 
"Snail", 
"Snake", 
"Snap", 
"Sneeze", 
"Snip", 
"Snook", 
"Snow", 
"Soft", 
"Song", 
"Soot", 
"Sorrel", 
"Spark", 
"Sparrow", 
"Speckle", 
"Spider", 
"Spike", 
"Spire", 
"Splash", 
"Spot", 
"Spotted", 
"Squirrel", 
"Stag", 
"Starling", 
"Star", 
"Stem", 
"Stoat", 
"Stone", 
"Stork", 
"Storm", 
"Stream", 
"Strike", 
"Stripe", 
"Stumpy", 
"Sun", 
"Sunny", 
"Swallow", 
"Swamp", 
"Swan", 
"Sweet", 
"Swift", 
"Tall", 
"Talon", 
"Tangle", 
"Tansy", 
"Tawny", 
"Thistle", 
"Thorn", 
"Thrift", 
"Thrush", 
"Thunder", 
"Tiger", 
"Timber", 
"Tiny", 
"Toad", 
"Torn", 
"Trout", 
"Tulip", 
"Tumble", 
"Turtle", 
"Twig", 
"Vine", 
"Violet", 
"Vixen", 
"Vole", 
"Wasp", 
"Wave", 
"Weasel", 
"Web", 
"Weed", 
"Wet", 
"Whisker", 
"Whisper", 
"Whistle", 
"White", 
"Whorl", 
"Wild", 
"Willow", 
"Wind", 
"Wish", 
"Wolf", 
"Wood", 
"Woolly", 
"Wren", 
"Yarrow", 
"Yellow", 
"Yew"
}

Suffixes = {
"bark", 
"beam", 
"bee", 
"belly", 
"berry", 
"bird", 
"blaze", 
"bloom", 
"blossom", 
"branch", 
"breeze", 
"briar", 
"bright", 
"brook", 
"burr", 
"burrow", 
"bush", 
"claw", 
"cloud", 
"crawl", 
"creek", 
"dapple", 
"dawn", 
"dusk", 
"dust", 
"ear", 
"eater", 
"eye", 
"eyes", 
"face", 
"fall", 
"fang", 
"feather", 
"fern", 
"fire", 
"fish", 
"flake", 
"flame", 
"flight", 
"flower", 
"foot", 
"frost", 
"fur", 
"gorse", 
"hawk", 
"haze", 
"heart", 
"ice",
"leaf", 
"leap", 
"leg", 
"light", 
"mask", 
"minnow", 
"mist", 
"moon", 
"mouse", 
"muzzle", 
"needle", 
"nose", 
"pad", 
"peak", 
"pelt", 
"petal", 
"pool", 
"poppy", 
"pounce", 
"puddle", 
"rose", 
"ripple", 
"runner", 
"scar", 
"scratch", 
"seed", 
"shade", 
"shell", 
"shine", 
"sight", 
"skip", 
"sky", 
"slip", 
"snout", 
"snow", 
"song", 
"speck", 
"speckle", 
"spirit", 
"splash", 
"spot", 
"spots", 
"spring", 
"stalk", 
"stem", 
"step", 
"stone", 
"storm", 
"stream", 
"strike", 
"stripe", 
"swoop", 
"tail", 
"talon", 
"teeth", 
"thistle", 
"thorn", 
"throat", 
"toe", 
"tooth", 
"tuft", 
"watcher", 
"water", 
"whisker", 
"whisper", 
"whistle", 
"willow", 
"wind", 
"wing", 
"wish"
}

--order this with the images by index
Pelts = {
	"Grey",
	"Brown",
	"White",
	"Tortieshell", 
	"White Tortieshell"
}

Eyecolors = {
	"Blue",
	"Amber",
	"Brown"
}

--turn this into a set or something
Roles = Array:new({"Leader", "Deputy", "Medicine Cat", "Warrior", "Apprentice", "Kit", "Elder"})

CatImages = {
	love.graphics.newImage("Images/catimage/catgreyidle.png"),
	love.graphics.newImage("Images/catimage/catgreyidle_unconcious.png"),
	love.graphics.newImage("Images/catimage/catbrownidle.png"),
	love.graphics.newImage("Images/catimage/catbrownidle_unconcious.png"), 
	love.graphics.newImage("Images/catimage/catwhiteidle.png"),
	love.graphics.newImage("Images/catimage/catwhiteidle_unconcious.png"),
	love.graphics.newImage("Images/catimage/cattortieidle.png"),
	love.graphics.newImage("Images/catimage/cattortieidle_unconcious.png"), 
	love.graphics.newImage("Images/catimage/catcalicoidle.png"),
	love.graphics.newImage("Images/catimage/catcalicoidle_unconcious.png")
}

ClanImages = {
	love.graphics.newImage("Images/ThunderclanSymbol.png"), 
	love.graphics.newImage("Images/RiverclanSymbol.png"),
	love.graphics.newImage("Images/WindclanSymbol.png"),
	love.graphics.newImage("Images/ShadowclanSymbol.png")
}

Decals = {
	love.graphics.newImage("Images/decals/blood_floor_small_1.png"), 
	love.graphics.newImage("Images/decals/blood_floor_small_2.png"), 
	love.graphics.newImage("Images/decals/blood_floor_small_3.png"), 
}

Claws = {
	["sheathed"] = love.graphics.newImage("Images/mouthbox_paw.png"),
	["unsheathed"] = love.graphics.newImage("Images/mouthbox_paw_unsheathed.png")
}

TextLine = love.graphics.newImage("Images/text_line.png")

SaveNumbers = {
	love.graphics.newImage("Images/numbers/one.png"),
	love.graphics.newImage("Images/numbers/two.png"),
	love.graphics.newImage("Images/numbers/three.png"),
	love.graphics.newImage("Images/numbers/four.png"),
	love.graphics.newImage("Images/numbers/five.png"),
	love.graphics.newImage("Images/numbers/six.png"),
	love.graphics.newImage("Images/numbers/seven.png"),
	love.graphics.newImage("Images/numbers/eight.png"),
	love.graphics.newImage("Images/numbers/nine.png"),
	love.graphics.newImage("Images/numbers/ten.png"),
}

AfflictionSymbols = {
	["Heavy bleeding"] = "B!+",
	["Bleeding"] = "B!~",
	["Pale"] = "Pal",
	["Faint"] = "Fnt",
	["Paralyzed"] = "Pz+",
	["Partially paralyzed"] = "Pz~",
	["Sluggish"] = "Slg",
	["Completely numb"] = "Nm+",
	["Partially numb"] = "Nm~",
	["Slightly numb"] = "Nm",
	["Serious fever"] = "F!",
	["Moderate fever"] = "F+",
	["Slight fever"] = "F~",
	["Dizzy"] = "Dz",
	["Extreme pain"] = "Pn!",
	["Moderate pain"] = "Pn+",
	["Slight pain"] = "Pn~",
	["Stunned"] = "St",
	["Overexerted"] = "Ovx",
	["Exhausted"] = "Exh",
	["Tired"] = "Tir",
	["Drowning"] = "Dr",
	["Winded"] = "Wd",
	["Cannot breathe"] = "Br",
	["Trouble breathing"] = "Br",
	["Dehydrated"] = "T!",
	["Thirsty"] = "T~",
	["Starving"] = "H!",
	["Hungry"] = "H~",
	["Very drowsy"] = "Dw",
	["Drowsy"] = "Dw",
	["Nauseous"] = "Na",
	["Vision lost"] = "V",
	["Vision impaired"] = "V",
	["Vision somewhat impaired"] = "V",
	["Spilled (Popped out)"] = "P",
	["Cannot stand"] = "Sx",
	["Stand impaired"] = "S~",
	["Cannot grasp"] = "Gx",
	["Grasp impaired"] = "G~",
	["Cannot fly"] = "Fx",
	["Flight impaired"] = "F~",
	["Motor nerve severed"] = "Mn",
	["Sensory nerve severed"] = "Sn",
	["Major artery torn"] = "A!",
	["Artery torn"] = "A+",
	["Overlapping fracture"] = "Of",
	["Compound fracture"] = "Cf",
	["Torn tendon"] = "Tn",
	["Tendon strain"] = "Tn",
	["Tendon bruise"] = "Tn",
	["Torn ligament"] = "Lg",
	["Ligament strain"] = "Lg",
	["Ligament bruise"] = "Lg",
	["Need setting"] = "Ns",
	["Broken tissue"] = "X!",
	["Heavy damage"] = "D!",
	["Moderate damage"] = "D+",
	["Light damage"] = "D~",
	["Partially broken tissue"] = "X~",
	["Extreme pain"] = "Pb!",
	["Moderate pain"] = "Pb+",
	["Minor pain"] = "Pb~",
	["Extreme swelling"] = "Sw!",
	["Medium swelling"] = "Sw+",
	["Minor swelling"] = "Sw~",
	["Infection"] = "In"
}